name = "workers-airtable-form"
compatibility_date = "2023-01-17"
type = "javascript"
account_id = "cb66508557465a58138cda4ee0318e3b"
workers_dev = true

[vars]
AIRTABLE_BASE_ID = "appIKs6nnmXmkwB1N"
AIRTABLE_TABLE_NAME = "AirtableExample"
FORM_URL = "www.google.com" 